# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/configuration/app.html

# The name of this app. Must be unique within a project.
name: 'mitr'

# The runtime the application uses.
type: 'php:8.0'

dependencies:
  php:
    composer/composer: '^2'

runtime:
  # Enable the redis extension so Drupal can communicate with the Redis cache.
  extensions:
    - apcu
    - ldap
    - xsl

# The size of the persistent disk of the application (in MB).
disk: 5120

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  # Data directory for the sqlite databases and multisite files.
  '/data':
    source: local
    source_path: 'data'
  # Drupal gets its own dedicated tmp directory. The settings.platformsh.php
  # file will automatically configure Drupal to use this directory.
  '/tmp':
    source: local
    source_path: 'tmp'
  # Private file uploads are stored outside the web root. The settings.platformsh.php
  # file will automatically configure Drupal to use this directory.
  '/private':
    source: local
    source_path: 'private'
  # Drush needs a scratch space for its own caches.
  '/.drush':
    source: local
    source_path: 'drush'
  # Drush will try to save backups to this directory, so it must be
  # writeable even though you will almost never need to use it.
  '/drush-backups':
    source: local
    source_path: 'drush-backups'

# Configuration of the build of this application.
build:
  # Automatically run `composer install` on every build.
  flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
  # The build hook runs after Composer to finish preparing up your code.
  # No services are available but the disk is writeable.
  build: |
      set -e
  # The deploy hook runs after your application has been deployed and started.
  # Code cannot be modified at this point but the database is available.
  # The site is not accepting requests while this script runs so keep it
  # fast.
  deploy: |
    set -e
    php ./drush/platformsh_generate_drush_yml.php
    cd web
    drush -y -l emhrm cache-rebuild
    drush -y -l emhrm updatedb
    drush -y -l emhrm config-import

# The configuration of app when it is exposed to the web.
web:
  locations:
    # All requests not otherwise specified follow these rules.
    '/':
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: 'web'

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m

      # Redirect any incoming request to Drupal's front controller.
      passthru: '/index.php'

      # Deny access to all static files, except those specifically allowed below.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    # The files directory has its own special configuration rules.
    '/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 5m
      passthru: '/index.php'
      root: 'data/files'

      # Do not execute PHP scripts from the writeable mount.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/files/(css|js)':
          expires: 2w

# Set the timezone for cron jobs.
timezone: "America/New_York"

variables:
  env:
    # This is used by the ilr-profiles-data-feed cron and script.
    OUTPUT_DIR: "/app/data/files/default/"

crons:
  # Run Drupal's cron tasks every 30 minutes.
  drupal:
    spec: '*/30 * * * *'
    cmd: 'drush -l emhrm core-cron'
  collegenet-import:
    # Run EMHRM CollegeNET importer every day at 7:05 and 12:05.
    spec: '5 7,12 * * *'
    cmd: |
      if [ "$PLATFORM_ENVIRONMENT_TYPE" = production ]; then
        drush -l emhrm collegenet2sf:run
      fi
  ilr-profiles-data-feed:
    # Run activity insight/ldap profile importer every morning at 8:35.
    spec: '35 8 * * *'
    cmd: |
      cd scripts/ilr-profiles-data-pull/
      php ./pull_people_data.php
